### ISSUE TITLE
Product Cataloque Design: (Need Clarification) It says from the title it is a catalogue but based from the design implied it is a product listing, and seems like the duplicate of the Product Listing Design, Maybe this is the reason why there's no implemeted page for Catalogue Listing?

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Ice-and-Oven-Technologies#104]
![image](https://cloud.githubusercontent.com/assets/13363508/10963969/06237940-83df-11e5-882f-5d3cef475362.png)

**Comment by isaq-titan** [comment]
Scoping and Implementation has been done as per the design and not by the file names.

**Comment by maehtitan** [comment]
What file names you mean? Project scope should be updated if there is changes and also for documentation purposes.

**Comment by maehtitan** [comment]
Yes it has been done but project scope mentioned a catalogue. Please kindly update the scope

**Comment by isaq-titan** [comment]
@maehtitan The scope has been updated, please check it.

**Comment by maehtitan** [comment]
Thanks
