### ISSUE TITLE
Phone Numbers: Click to call Phone number shouldn't have open and close parenthesis, please strip it down

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Ice-and-Oven-Technologies#111]
Just like this one: 
![image](https://cloud.githubusercontent.com/assets/13363508/11082712/99f2bcee-8862-11e5-83fe-2856e48b2f69.png)

These are the numbers that needs to strip down the parenthesis:
![image](https://cloud.githubusercontent.com/assets/13363508/11082722/b3c54754-8862-11e5-9992-9efd000df0ec.png)
![image](https://cloud.githubusercontent.com/assets/13363508/11082727/bd63b52a-8862-11e5-8223-e75710b32d18.png)
![image](https://cloud.githubusercontent.com/assets/13363508/11082732/c724862a-8862-11e5-9e16-918add197bdd.png)

**Comment by maehtitan** [comment]
Phone number in header NZ 0800 770 723

**Comment by isaq-titan** [comment]
I have already fixed it and it does not show in my Ipad here. - Please find the attached screenshot for reference.
![img_0986](https://cloud.githubusercontent.com/assets/13450822/11140630/ad5228d2-8a02-11e5-918e-296daba77265.PNG)
