### ISSUE TITLE
Product: Missing product catalogue, I created a new category named Test Category & Sub-Category but I dunno where to view the one I created coz I haven't found any category listing, So what I did is to try checking this page http://ice-oven-technologies.stage.titanweb.com.au/products/ but no appropriate layout, 

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Ice-and-Oven-Technologies#67]
![image](https://cloud.githubusercontent.com/assets/13363508/10934442/e5bfbd72-831a-11e5-8076-feb9b78aa2dc.png)

**Comment by isaq-titan** [comment]
As per the scope and the design brief only two categories has to be displayed ( ICE and OVEN ), so according to this there is no page where we have can display any further categories.

**Comment by maehtitan** [comment]
@isaq-titan Please read again the project scope, it is not what the scope stated, its obviously a category. Please kindly update the scope.
https://docs.google.com/spreadsheets/d/1nVk_WpHttHk3h6tArrJdHvGDag_75YHOHelV40N_s5w/edit?pli=1#gid=859037033

Thanks

**Comment by isaq-titan** [comment]
@maehtitan The scope has been updated, please check it.
