### ISSUE TITLE
Product Catalogue, Product listing view & Product Single View: Hard cropped is avoided and not advisable coz it will not display the whole dimensions of the images

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Ice-and-Oven-Technologies#68]
![image](https://cloud.githubusercontent.com/assets/13363508/10934600/c2c76526-831b-11e5-95c4-a14ffd654230.png)
![image](https://cloud.githubusercontent.com/assets/13363508/10963169/0cd5fd2c-83d9-11e5-8eb6-005d88aea605.png)

**Comment by maehtitan** [comment]
Still now fixed, images still cropped
http://ice-oven-technologies.stage.titanweb.com.au/product-category/test-category/sub-category/

**Comment by isaq-titan** [comment]
It is working fine,old Images for the categories and products has to be deleted and re-uploaded again.
