### ISSUE TITLE
Lead-ins (Home page): Post titles are overlapping with images on IE 9,10 & 11.

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Ice-and-Oven-Technologies#7]
IE 11

![lead-ins-ie11_001](https://cloud.githubusercontent.com/assets/13309730/10477617/33da40ce-7275-11e5-8821-b0fd7dc8356f.png)

IE 9

![lead-ins-ie11](https://cloud.githubusercontent.com/assets/13309730/10477624/4597a7ac-7275-11e5-85b3-afa368cbe714.png)

**Comment by mahender-sowedane** [comment]
IE browser issues are not fixed properly, kindly fix it
thanks!

**Comment by ravi-josyula** [comment]
Still bug is not fixed.
