### ISSUE TITLE
Homepage & Inner Page - Solutions Sidebar - Mobile: Image uploaded are compressed at the edge of the device

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Ice-and-Oven-Technologies#80]
Devices: Itouch5 & S4 (landscape)

![image](https://cloud.githubusercontent.com/assets/13363508/10959572/2681f010-83b5-11e5-9426-cf73554f3f7c.png)

**Comment by isaq-titan** [comment]
Please check the attached PSD which is also not having much gaps between the text and images .
![homepage-psd-screenshot](https://cloud.githubusercontent.com/assets/13450822/11040717/bbf4eca2-8733-11e5-8a17-076ec777e2cc.jpg)
