### ISSUE TITLE
Contact - Send Form Process: Is it only one "Send to Email" they are using? Because there are 3 locations and 3 different Business Details, They might used the repeater in adding emails in notifications. Please see screenshot sample site below 

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Ice-and-Oven-Technologies#91]
![image](https://cloud.githubusercontent.com/assets/13363508/10962045/c2bc4236-83cf-11e5-99e2-3ecc3a7b74d2.png)

**Comment by isaq-titan** [comment]
I have added the repeater field but currently gave only info@iceandoven.com.au for all the three fields client can change it accordingly.

**Comment by maehtitan** [comment]
Thanks :)
